-- MySQL Script generated by MySQL Workbench
-- Sat Dec  8 14:04:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `nivel_acesso` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `qtd_tentativa_login` SMALLINT NULL,
  `esta_logado` TINYINT NULL,
  `data_permissao_login` DATETIME NULL,
  `fl_ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `Usuario_id` BIGINT(10) NOT NULL,
  `credito` DOUBLE NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  CONSTRAINT `fk_Aluno_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Usuario_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `Usuario_id` BIGINT(10) NOT NULL,
  `Administrador_Usuario_id` BIGINT(10) NULL,
  `data_aprovacao_administrador` DATETIME NULL,
  PRIMARY KEY (`Usuario_id`),
  INDEX `fk_Professor_Administrador1_idx` (`Administrador_Usuario_id` ASC),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Administrador1`
    FOREIGN KEY (`Administrador_Usuario_id`)
    REFERENCES `mydb`.`Administrador` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Professor_Usuario_id` BIGINT(10) NOT NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `aprovado_pelo_administrador` TINYINT NOT NULL,
  `disponivel` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Curso_Professor1`
    FOREIGN KEY (`Professor_Usuario_id`)
    REFERENCES `mydb`.`Professor` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `Curso_id` BIGINT(10) NOT NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `texto` TEXT NOT NULL,
  `link_video_aula` VARCHAR(200) NULL,
  INDEX `fk_Aula_Curso1_idx` (`Curso_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Aula_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Imagens` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Imagens` (
  `Aula_id` BIGINT(10) NOT NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  INDEX `fk_Imagens_Aula1_idx` (`Aula_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Imagens_Aula1`
    FOREIGN KEY (`Aula_id`)
    REFERENCES `mydb`.`Aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_Compra_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno_Compra_Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_Compra_Curso` (
  `Aluno_Usuario_id` BIGINT(10) NOT NULL,
  `Curso_id` BIGINT(10) NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `valor_compra` DOUBLE NOT NULL,
  PRIMARY KEY (`Aluno_Usuario_id`, `Curso_id`),
  INDEX `fk_Aluno_has_Curso_Curso1_idx` (`Curso_id` ASC),
  INDEX `fk_Aluno_has_Curso_Aluno1_idx` (`Aluno_Usuario_id` ASC),
  CONSTRAINT `fk_Aluno_has_Curso_Aluno1`
    FOREIGN KEY (`Aluno_Usuario_id`)
    REFERENCES `mydb`.`Aluno` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Curso_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Email` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Email` (
  `Curso_id` BIGINT(10) NOT NULL,
  `Professor_Usuario_id` BIGINT(10) NOT NULL,
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `mensagem` TEXT NOT NULL,
  `data_envio` DATETIME NOT NULL,
  INDEX `fk_Curso_has_Professor_Professor1_idx` (`Professor_Usuario_id` ASC),
  INDEX `fk_Curso_has_Professor_Curso1_idx` (`Curso_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Curso_has_Professor_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Professor_Professor1`
    FOREIGN KEY (`Professor_Usuario_id`)
    REFERENCES `mydb`.`Professor` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `idLog` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `Usuario_id` BIGINT(10) NOT NULL,
  `data_hora` DATETIME NOT NULL DEFAULT NOW(),
  `acao` TEXT NOT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `fk_Log_Usuario1_idx` (`Usuario_id` ASC),
  CONSTRAINT `fk_Log_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
